services:
  mongod:
    image: mongodb/mongodb-community-server:latest
    container_name: mongod-community
    command: >-
      mongod --config /etc/mongod.conf --replSetMember=mongod.search-community:27017
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - mongod_data:/data/db
      - ./mongod.conf:/etc/mongod.conf:ro
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    networks:
      - search-community
    restart: unless-stopped

  mongot:
    # image: mongodb/mongodb-community-search:latest
    build:
      context: .
      dockerfile: Dockerfile.mongot
    container_name: mongot-community-pupr
    networks:
      - search-community
    volumes:
      - mongot_data:/data/mongot
      - ./mongot.conf:/mongot-community/config.default.yml
      # - ./pwfile:/mongot-community/pwfile:ro
    depends_on:
      - mongod
    ports:
      - 27028:27028 # Query server port from config
      - 9946:9946 # Metrics port from config
    restart: unless-stopped

  smartlp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartlp
    depends_on:
      - mongod
      - mongot
    environment:
      - MONGO_URI=mongodb://mongod:27017/?directConnection=true
      - SMARTLP_ARCHIVE=/smartlp.archive
      - APP_HOST=0.0.0.0
      - APP_PORT=8800
      - APP_DEBUG=False
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./smartlp.archive:/smartlp.archive:ro
    ports:
      - 8800:8800
    networks:
      - search-community
    restart: unless-stopped

volumes:
  mongod_data:
  mongot_data:


networks:
  search-community:
    name: search-community
    external: true # Use an external network if it exists. Comment this line if you want to create a new network.
